sudo: false
language: cpp

addons:
 apt:
  packages:
   - qt5-qmake
   - clang-3.7

notifications: newer

env: COMPILER=clang++-3.7

os:
  - osx

compiler:
  - clang

before_install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew update'

install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew install qt5'
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew link --force qt5'

script:
  - cd Tempest
  - qmake Tempest.pro
  - make
