sudo: false
language: cpp

addons:
 apt:
  packages:
   - qt5-qmake
   - clang-3.7

notifications: newer

os:
  - osxs

compiler:
  - clang

before_install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew update'

install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew install qt5'
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew link --force qt5'

script:
  - cd Tempest
  - qmake Tempest.pro -r -spec macx-clang CONFIG+=x86_64
  - make
