sudo: false
language: cpp

addons:
 apt:
  packages:
   - qt5-qmake
   - clang-3.7

notifications: newer

os:
  - osx

compiler:
  - clang

before_install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew update'

install:
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew install qt5'
 - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew link --force qt5'
 # clang 3.7
 - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
 - clang --version

script:
  - cd Tempest
  - qmake Tempest.pro -r -spec macx-clang CONFIG+=x86_64
  - make

before_deploy:
  - zip     release.zip ./lib
  - zip -ur release.zip ./Tempest/include

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
    - "release.zip"

  skip_cleanup: true
  on:
    branch: release
    tags: true
