install:
  - mkdir utils
  - cd utils
  - appveyor DownloadFile http://camlorn.net/appveyor/jom.exe
  - cd ..
  - set QTDIR=C:\Qt\5.6\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;c:\projects\tempest\utils

environment:
  matrix:
    - QMAKE_FLAGS: "CONFIG+=debug"
      QMAKE_SPEC : "-r -spec win32-msvc2015"
      VSVER: 14.0 # Visual Studio 2015
    - QMAKE_FLAGS: ""
      QMAKE_SPEC : "-r -spec win32-msvc2015"
      VSVER: 14.0 # Visual Studio 2015

before_build:
  # Prepare the out-of-source build directory.
  - mkdir lib

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" x86'
  - cd Tempest
  - qmake Tempest.pro  %QMAKE_SPEC%  %QMAKE_FLAGS% "CONFIG+=msvc_static"
  - jom.exe
  - cd ../Examples
  - qmake examples.pro -r -spec win32-msvc2015 %QMAKE_FLAGS%
  - jom.exe
  - cd ../
  - echo lib
  - dir /s /b

artifacts:
  - path: lib\Tempest.dll
  - path: lib\Tempest.lib
  - path: lib\Tempest.a
