install:
  - mkdir utils
  - cd utils
  - appveyor DownloadFile http://camlorn.net/appveyor/jom.exe
  - cd ..
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;c:\projects\tempest\utils

environment:
  matrix:
    - QMAKE_SPEC : "win32-msvc2015"
      QTDIR: C:\Qt\5.6\msvc2015
      VSVER: 14.0 # Visual Studio 2015

    - QMAKE_SPEC : "win32-g++"
      QTDIR: C:\Qt\5.6\mingw49_32

    - QMAKE_SPEC : "android-g++"
      QTDIR: C:\Qt\5.6\android_armv7

configuration:
  - debug
  - release

before_build:
  # Prepare the out-of-source build directory.
  - mkdir lib
  # Setup the build toolchains
  - set PATH=%PATH%;%QTDIR%\bin
  - '%QTDIR%\bin\qtenv2.bat'
  - '"C:\Program Files (x86)\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" x86'

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\Tempest
  - qmake Tempest.pro -r -spec %QMAKE_SPEC% CONFIG+=%CONFIGURATION%
  - jom.exe
  - cd ../Examples
  - qmake examples.pro -r -spec %QMAKE_SPEC% CONFIG+=%CONFIGURATION%
  - jom.exe
  - cd ../

artifacts:
  - path: lib\Tempest.dll
  - path: lib\Tempest.lib
  - path: lib\Tempest.a
